#version: '3.8'
#
#services:
#  sqlserver:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    container_name: sql
#    environment:
#      - ACCEPT_EULA=Y
#      - SA_PASSWORD=Password123
#    ports:
#      - "1433:1433"
#    volumes:
#      - mssql_data:/var/opt/mssql
#
#volumes:
#  mssql_data:
#    driver: local
